export const searchData = [
  {
    title: "Home",
    description: "Go to the portfolio welcome page",
    path: "/",
    keywords: [
      "home",
      "start",
      "welcome",
      "portfolio",
      "shelbys",
      "systems engineering",
    ],
  },
  {
    title: "About",
    description: "Learn more about shelbys and the systems engineering focus",
    path: "/about",
    keywords: [
      "about",
      "background",
      "bio",
      "profile",
      "systems engineering",
      "kuwait",
    ],
  },
  {
    title: "Education",
    description: "View the Systems Engineering path at AUK",
    path: "/education",
    keywords: [
      "education",
      "university",
      "auk",
      "american university of kuwait",
      "degree",
      "coursework",
    ],
  },
  {
    title: "Experience",
    description: "Review practical build and learning experience",
    path: "/experience",
    keywords: ["experience", "work", "builds", "projects", "lab"],
  },
  {
    title: "Skills",
    description: "Explore systems, software, and infrastructure skills",
    path: "/skills",
    keywords: [
      "skills",
      "react",
      "javascript",
      "python",
      "linux",
      "aws",
      "git",
    ],
  },
  {
    title: "Projects",
    description: "View shipped tools and prototypes",
    path: "/projects",
    keywords: [
      "projects",
      "docucraft",
      "pdf",
      "inventory",
      "chess",
      "sandboxearth",
      "terrainintel",
      "code",
    ],
  },
  {
    title: "DocuCraft",
    description: "Privacy-first PDF and image toolkit that runs in the browser",
    path: "/projects",
    keywords: ["docucraft", "pdf", "merge", "compress", "privacy", "tools"],
  },
  {
    title: "SandboxEarth",
    description: "Themed interactive map with GTA and RDR2 aesthetics",
    path: "/projects",
    keywords: ["sandboxearth", "maps", "gta", "rdr2"],
  },
  {
    title: "Chess Companion",
    description: "Offline chess app with bots and four game modes",
    path: "/projects",
    keywords: ["chess", "games", "bots"],
  },
  {
    title: "Certificates",
    description: "View learning milestones and certificates in progress",
    path: "/certificates",
    keywords: ["certificates", "aws", "cloud", "learning"],
  },
  {
    title: "Contact",
    description: "Email shelbys or send a message",
    path: "/contact",
    keywords: ["contact", "email", "collaboration", "info@shelbys.dev"],
  },
];
